"""empty message

Revision ID: 78adf2d6db0a
Revises: 385a5d33bc4c
Create Date: 2018-10-11 18:21:51.882788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78adf2d6db0a'
down_revision = '385a5d33bc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'age')
    # ### end Alembic commands ###
