"""empty message

Revision ID: bad073a01ab4
Revises: 78adf2d6db0a
Create Date: 2018-10-17 19:50:37.783088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad073a01ab4'
down_revision = '78adf2d6db0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('owners', sa.Column('state', sa.String(length=128), nullable=True))
    op.add_column('owners', sa.Column('zip_code', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'zip_code')
    op.drop_column('owners', 'state')
    op.drop_column('owners', 'city')
    # ### end Alembic commands ###
